[package]
name = "gbsabiru"
version = "0.1.0"
authors = ["Nathan <naleba97@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enum_primitive = "0.1.1"
num = "0.3.0"
